server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yuedong?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: xiao
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

jwt:
  secret: yuedong-sport-checkin-secret-key-2026
  expiration: 604800000

logging:
  level:
    com.yuedong: debug
